version: "3.5"
services:
  host-database:
    container_name: host_db
    build: .
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: secret
      PG_REP_USER: rep
      PG_REP_PASSWORD: repsecret
      REP_SLOT_NAME: updater
    expose:
     - 6662
    ports:
     - "6662:5432"
volumes:
  data: